### ISSUE TITLE
Make segfault

### ISSUE THREAD

**Issue by nirs** [RamenDR/recipe#27]
```
$ make
/home/nsoffer/src/recipe/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa04ede]

goroutine 179 [running]:
go/types.(*Checker).handleBailout(0xc0002c0e00, 0xc0008ddd40)
	/usr/local/go/src/go/types/check.go:367 +0x88
panic({0xbbb960?, 0x129cce0?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0xdb1238, 0x12a5400})
	/usr/local/go/src/go/types/sizes.go:228 +0x31e
go/types.(*Config).sizeof(...)
	/usr/local/go/src/go/types/sizes.go:333
go/types.representableConst.func1({0xdb1238?, 0x12a5400?})
	/usr/local/go/src/go/types/const.go:76 +0x9e
go/types.representableConst({0xdb74d8, 0x12715a0}, 0xc0002c0e00, 0x12a5400, 0x0)
	/usr/local/go/src/go/types/const.go:92 +0x192
go/types.(*Checker).arrayLength(0xc0002c0e00, {0xdb5818, 0xc0011aa700?})
	/usr/local/go/src/go/types/typexpr.go:510 +0x2d3
go/types.(*Checker).typInternal(0xc0002c0e00, {0xdb3e68, 0xc0011a6d20}, 0x0)
	/usr/local/go/src/go/types/typexpr.go:299 +0x49d
go/types.(*Checker).definedType(0xc0002c0e00, {0xdb3e68, 0xc0011a6d20}, 0xc0008dd328?)
	/usr/local/go/src/go/types/typexpr.go:180 +0x37
go/types.(*Checker).varType(0xc0002c0e00, {0xdb3e68, 0xc0011a6d20})
	/usr/local/go/src/go/types/typexpr.go:145 +0x25
go/types.(*Checker).structType(0xc0002c0e00, 0xc000e71f50, 0xc000e71f50?)
	/usr/local/go/src/go/types/struct.go:113 +0x19f
go/types.(*Checker).typInternal(0xc0002c0e00, {0xdb3dd8, 0xc0008f3e00}, 0xc000e6f450)
	/usr/local/go/src/go/types/typexpr.go:316 +0x1345
go/types.(*Checker).definedType(0xc0002c0e00, {0xdb3dd8, 0xc0008f3e00}, 0xc84988?)
	/usr/local/go/src/go/types/typexpr.go:180 +0x37
go/types.(*Checker).typeDecl(0xc0002c0e00, 0xc000e6f450, 0xc001193940, 0x0)
	/usr/local/go/src/go/types/decl.go:615 +0x44d
go/types.(*Checker).objDecl(0xc0002c0e00, {0xdbc9d8, 0xc000e6f450}, 0x0)
	/usr/local/go/src/go/types/decl.go:197 +0xa7f
go/types.(*Checker).packageObjects(0xc0002c0e00)
	/usr/local/go/src/go/types/resolver.go:681 +0x425
go/types.(*Checker).checkFiles(0xc0002c0e00, {0xc000be0d20, 0x3, 0x3})
	/usr/local/go/src/go/types/check.go:408 +0x1a5
go/types.(*Checker).Files(...)
	/usr/local/go/src/go/types/check.go:372
sigs.k8s.io/controller-tools/pkg/loader.(*loader).typeCheck(0xc000371050, 0xc000678720)
	/home/nsoffer/go/pkg/mod/sigs.k8s.io/controller-tools@v0.10.0/pkg/loader/loader.go:286 +0x36a
sigs.k8s.io/controller-tools/pkg/loader.(*Package).NeedTypesInfo(0xc000678720)
	/home/nsoffer/go/pkg/mod/sigs.k8s.io/controller-tools@v0.10.0/pkg/loader/loader.go:99 +0x39
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check(0xc000a930b0, 0xc000678720)
	/home/nsoffer/go/pkg/mod/sigs.k8s.io/controller-tools@v0.10.0/pkg/loader/refs.go:268 +0x2b7
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check.func1(0x4c?)
	/home/nsoffer/go/pkg/mod/sigs.k8s.io/controller-tools@v0.10.0/pkg/loader/refs.go:262 +0x53
created by sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check in goroutine 29
	/home/nsoffer/go/pkg/mod/sigs.k8s.io/controller-tools@v0.10.0/pkg/loader/refs.go:260 +0x1c5
make: *** [Makefile:106: generate] Error 2
```

Fixed by #25 commit https://github.com/RamenDR/recipe/pull/25/commits/f907c08034434fa8fb49b71db85943abd4e6367d

**Comment by nirs** [comment]
Fixed by #28
